# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e78e852eeaf9f396ba225a1e92f526b1f1dddc14786692e6d373b825ceabcecf4109f5df97abab30bc1ec1ffcb40e48aa3e1127ca11fc34f0f9cf81cefcc0877

test:
  secret_key_base: 3e32b3a6ea1deaff75af327a69aaa725b3a478a789dd53f2290dcda5ec0e141bb2439c0cc777727c23c36004612322347dc4bfaed58d1f4c29e038f7aa64ce84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
